#!/bin/sh
regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]]
then
    echo Your email $email satisfy Git policy
    exit 0
else
    echo "Your email $email doesn't satisfy Git policy"
    exit 1
fi